data_transformation:
  outputs:
    dev:
      dbname: dw
      host: dpg-d2kafj24d50c73fl7b2g-a.oregon-postgres.render.com
      pass: "{{ env_var('POSTGRE_PASSWORD') }}"
      port: 5432
      schema: DMO
      threads: 1
      type: postgres
      user: admin
  target: dev
